--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are willing drive far for ice cream."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://pd-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "March 6-8, 2018"
  description: "This workshop will cover the ..."
  customerLogo: ""
  instructors: 
    - 
      name: "Jared Gordon"
      title: "Platform Engineer"
      email: jgordon@pivotal.io
    - 
      name: "Chris Decelles"
      title: "Platform Engineer"
      email: cdecelles@pivotal.io    
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "BOSH"
      url: "http://bosh.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  sessions:
    - 
      id: "pks"
      name: "PKS Workshop"
      description: "April 12, 2018"
      topics:
      -
        id: "intro"
        title: "9:15 - 9:30"
        description: "Introductions - Linh Nguyen"
      -
        id: "bckgrd"
        title: "9:30 - 10:30"
        description: "Background info on PKS & PAS - Chris Saunders"
      -
        id: "break1"
        title: "10:30 - 10:45"
        description: "Break"
      -
        id: "morning-demo"
        title: "11:00 - 12:00"
      -
        id: "pks-workshop-morning"
        title: "PKS Part I - Jared & Chris D."
      -
        id: "pks-nginx-lab"
      -
        id: "pks-elastic-lab"
      -
        id: "lunch"
        title: "Lunch - 12:00 - 1:00"
      -
        id: "pks-afternoon"
        title: "1:00 - 1:45"
      -
        id: "pks-workshop-afternoon"
        title: "PKS Part II - Jared & Chris D."
      -
        id: "afternoon-demo"
        title: "1:45 - 3:00" 
        description: "Demos - Jared & Chris D."
      -
        id: "pks-suitecrm-lab"
      -
        id: "pks-spark-lab"
      -
        id: "pks-wildfly-lab"
      -
        id: "hack"
        title: "3:00 - ??:??"
        description: "Interactive hackathon and Q&A"
